### ISSUE TITLE
What kind of files are placed in 'trainB_label' mentioned in datasets.py? 

### ISSUE THREAD

**Issue by zhangsong1213** [fordevoted/UIESS#2]
What kind of files are placed in 'trainB_label' mentioned in datasets.py? This is not mentioned in the README.md.
If I want to train only with unpaired images (underwater images and clean images), how should I set up the dataset?

**Comment by fordevoted** [comment]
trainB  and trainB_label are the training synthesis underwater image and its in-air clean counterpart. We use EUVP dataset for the experiment.

Our method required paired synthesis data and  real-world underwater images to perform domain adaptation. If you have no synthesized paired data, we will suggest using EUVP or referring to underwater image synthesizing literature to generate such kind of data.

**Comment by zhangsong1213** [comment]
> trainB and trainB_label are the training synthesis underwater image and its in-air clean counterpart. We use EUVP dataset for the experiment.
> 
> Our method required paired synthesis data and real-world underwater images to perform domain adaptation. If you have no synthesized paired data, we will suggest using EUVP or referring to underwater image synthesizing literature to generate such kind of data.

Thanks a lot for your answer
